codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 30%
        threshold: 1%
        base: auto
        if_ci_failed: error

    patch:
      default:
        target: 50%
        threshold: 5%
        base: auto
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "**/__tests__/**"
  - "**/__mocks__/**"
  - "src/app/**"
  - "**/*.d.ts"
  - "**/types.ts"
  - "**/*.config.ts"
  - "**/*.config.js"
  - "**/node_modules/**"

flags:
  unittests:
    paths:
      - src/
    carryforward: true

github_checks:
  annotations: true
