import { beforeEach, describe, expect, it, vi } from 'vitest';
import {
  getWeeklyPlanningEndpoint,
  updateWeeklyPlanningEndpoint,
  upsertPlanningSlotEndpoint,
  autofillPlanningEndpoint,
} from '../studyPlanningEndpoints';
import type { WeeklyPlanResponse, StudyPlanSlotInput } from '../../services/StudyPlanningService';

const serviceInstance = {
  getWeeklyPlan: vi.fn(),
  updateWeeklyPlan: vi.fn(),
  upsertSlot: vi.fn(),
  generateAutofillSuggestions: vi.fn(),
};

vi.mock('../../services/StudyPlanningService', () => ({
  StudyPlanningService: vi.fn(() => serviceInstance),
}));

const createMockResponse = () => {
  const res = {
    status: vi.fn().mockReturnThis(),
    json: vi.fn().mockReturnThis(),
  };

  return res as unknown as Parameters<typeof getWeeklyPlanningEndpoint.handler>[1];
};

describe('studyPlanningEndpoints', () => {
  const payloadStub = {} as any;

  beforeEach(() => {
    Object.values(serviceInstance).forEach((fn) => fn.mockReset());
  });

  describe('getWeeklyPlanningEndpoint', () => {
    it('refuse l\'accès si non authentifié', async () => {
      const req = {
        user: undefined,
        payload: payloadStub,
        query: {},
      } as any;

      const res = createMockResponse();

      await getWeeklyPlanningEndpoint.handler(req, res, vi.fn());

      expect(res.status).toHaveBeenCalledWith(401);
      expect(res.json).toHaveBeenCalledWith({
        success: false,
        error: 'Authentification requise',
      });
      expect(serviceInstance.getWeeklyPlan).not.toHaveBeenCalled();
    });

    it('retourne le planning hebdomadaire', async () => {
      const response: WeeklyPlanResponse = {
        plan: {
          id: 'plan-1',
          title: 'Planning',
          planType: 'weekly',
          status: 'active',
          user: 42,
          weekStart: '2024-01-08T00:00:00.000Z',
          weekEnd: '2024-01-14T23:59:59.999Z',
          slots: [],
          plannedDurationMinutes: 0,
          actualDurationMinutes: 0,
          autoGenerated: false,
          metadata: null,
        },
        weekStart: '2024-01-08T00:00:00.000Z',
        weekEnd: '2024-01-14T23:59:59.999Z',
        summary: { plannedMinutes: 0, completedMinutes: 0, slotsCount: 0 },
      };

      serviceInstance.getWeeklyPlan.mockResolvedValue(response);

      const req = {
        user: { id: 42 },
        payload: payloadStub,
        query: { weekStart: '2024-01-08' },
      } as any;

      const res = createMockResponse();

      await getWeeklyPlanningEndpoint.handler(req, res, vi.fn());

      expect(serviceInstance.getWeeklyPlan).toHaveBeenCalledWith('42', '2024-01-08');
      expect(res.status).toHaveBeenCalledWith(200);
      expect(res.json).toHaveBeenCalledWith({ success: true, ...response, hasPlan: true });
    });
  });

  describe('updateWeeklyPlanningEndpoint', () => {
    it('valide la présence de weekStart', async () => {
      const req = {
        user: { id: 42 },
        payload: payloadStub,
        body: { title: 'Planning' },
      } as any;

      const res = createMockResponse();

      await updateWeeklyPlanningEndpoint.handler(req, res, vi.fn());

      expect(res.status).toHaveBeenCalledWith(400);
      expect(res.json).toHaveBeenCalledWith({
        success: false,
        error: 'weekStart est requis',
      });
      expect(serviceInstance.updateWeeklyPlan).not.toHaveBeenCalled();
    });

    it('met à jour le planning avec succès', async () => {
      const response: WeeklyPlanResponse = {
        plan: {
          id: 'plan-1',
          title: 'Planning',
          planType: 'weekly',
          status: 'active',
          user: 42,
          weekStart: '2024-01-08T00:00:00.000Z',
          weekEnd: '2024-01-14T23:59:59.999Z',
          slots: [],
          plannedDurationMinutes: 0,
          actualDurationMinutes: 0,
          autoGenerated: false,
          metadata: null,
        },
        weekStart: '2024-01-08T00:00:00.000Z',
        weekEnd: '2024-01-14T23:59:59.999Z',
        summary: { plannedMinutes: 0, completedMinutes: 0, slotsCount: 0 },
      };

      serviceInstance.updateWeeklyPlan.mockResolvedValue(response);

      const req = {
        user: { id: '42' },
        payload: payloadStub,
        body: {
          weekStart: '2024-01-08T00:00:00.000Z',
          title: 'Planning mis à jour',
        },
      } as any;

      const res = createMockResponse();

      await updateWeeklyPlanningEndpoint.handler(req, res, vi.fn());

      expect(serviceInstance.updateWeeklyPlan).toHaveBeenCalledWith('42', {
        title: 'Planning mis à jour',
        weekStart: '2024-01-08T00:00:00.000Z',
      });
      expect(res.status).toHaveBeenCalledWith(200);
      expect(res.json).toHaveBeenCalledWith({ success: true, ...response });
    });
  });

  describe('upsertPlanningSlotEndpoint', () => {
    it('valide weekStart et slot', async () => {
      const req = {
        user: { id: 42 },
        payload: payloadStub,
        body: { weekStart: '2024-01-08' },
      } as any;

      const res = createMockResponse();

      await upsertPlanningSlotEndpoint.handler(req, res, vi.fn());

      expect(res.status).toHaveBeenCalledWith(400);
      expect(res.json).toHaveBeenCalledWith({
        success: false,
        error: 'slot est requis ou invalide',
      });
      expect(serviceInstance.upsertSlot).not.toHaveBeenCalled();
    });

    it('met à jour un créneau', async () => {
      const slot: StudyPlanSlotInput = {
        slotId: 'slot-1',
        title: 'Session',
        startsAt: '2024-01-09T18:00:00.000Z',
        durationMinutes: 60,
        activityType: 'study_session',
      };

      const response: WeeklyPlanResponse = {
        plan: {
          id: 'plan-1',
          title: 'Planning',
          planType: 'weekly',
          status: 'active',
          user: 42,
          weekStart: '2024-01-08T00:00:00.000Z',
          weekEnd: '2024-01-14T23:59:59.999Z',
          slots: [slot],
          plannedDurationMinutes: 60,
          actualDurationMinutes: 0,
          autoGenerated: false,
          metadata: null,
        },
        weekStart: '2024-01-08T00:00:00.000Z',
        weekEnd: '2024-01-14T23:59:59.999Z',
        summary: { plannedMinutes: 60, completedMinutes: 0, slotsCount: 1 },
      };

      serviceInstance.upsertSlot.mockResolvedValue(response);

      const req = {
        user: { id: 42 },
        payload: payloadStub,
        body: { weekStart: '2024-01-08', slot },
      } as any;

      const res = createMockResponse();

      await upsertPlanningSlotEndpoint.handler(req, res, vi.fn());

      expect(serviceInstance.upsertSlot).toHaveBeenCalledWith('42', '2024-01-08', slot);
      expect(res.status).toHaveBeenCalledWith(200);
      expect(res.json).toHaveBeenCalledWith({ success: true, ...response });
    });
  });

  describe('autofillPlanningEndpoint', () => {
    it('valide la présence de weekStart', async () => {
      const req = {
        user: { id: 42 },
        payload: payloadStub,
        body: { apply: true },
      } as any;

      const res = createMockResponse();

      await autofillPlanningEndpoint.handler(req, res, vi.fn());

      expect(res.status).toHaveBeenCalledWith(400);
      expect(res.json).toHaveBeenCalledWith({
        success: false,
        error: 'weekStart est requis',
      });
      expect(serviceInstance.generateAutofillSuggestions).not.toHaveBeenCalled();
    });

    it('génère des suggestions', async () => {
      const response = {
        suggestions: [],
        applied: false,
        plan: {
          id: 'plan-1',
          title: 'Planning',
          planType: 'weekly',
          status: 'active',
          user: 42,
          weekStart: '2024-01-08T00:00:00.000Z',
          weekEnd: '2024-01-14T23:59:59.999Z',
          slots: [],
          plannedDurationMinutes: 0,
          actualDurationMinutes: 0,
          autoGenerated: false,
          metadata: null,
        },
      } as any;

      serviceInstance.generateAutofillSuggestions.mockResolvedValue(response);

      const req = {
        user: { id: 42 },
        payload: payloadStub,
        body: { weekStart: '2024-01-08', apply: 'true', options: { preferredHour: 20 } },
      } as any;

      const res = createMockResponse();

      await autofillPlanningEndpoint.handler(req, res, vi.fn());

      expect(serviceInstance.generateAutofillSuggestions).toHaveBeenCalledWith(
        '42',
        '2024-01-08',
        { preferredHour: 20 },
        true
      );
      expect(res.status).toHaveBeenCalledWith(200);
      expect(res.json).toHaveBeenCalledWith({ success: true, ...response });
    });
  });
});
