import type { CollectionConfig } from 'payload';
import { authenticated } from '../access/authenticated';

export const StudyPlans: CollectionConfig = {
  slug: 'study-plans',
  labels: {
    singular: 'Planning d\'étude',
    plural: 'Plannings d\'étude',
  },
  admin: {
    useAsTitle: 'title',
    defaultColumns: ['title', 'planType', 'status', 'weekStart', 'user'],
    description: 'Organisation hebdomadaire et plannings de révision des étudiants',
    group: 'Apprentissage',
  },
  access: {
    read: ({ req }) => {
      if (req.user?.role === 'admin') return true;
      return { user: { equals: req.user?.id } };
    },
    create: authenticated,
    update: authenticated,
    delete: ({ req }) => req.user?.role === 'admin',
  },
  fields: [
    {
      name: 'title',
      label: 'Titre du planning',
      type: 'text',
      required: true,
    },
    {
      name: 'scheduleId',
      label: 'Identifiant planning (SRS)',
      type: 'text',
      admin: {
        description: 'Utilisé pour synchroniser les plannings automatiques de répétition espacée',
        condition: (data) => data.planType === 'spaced_repetition',
      },
    },
    {
      name: 'planType',
      label: 'Type de planning',
      type: 'select',
      required: true,
      defaultValue: 'weekly',
      options: [
        { label: 'Planning hebdomadaire', value: 'weekly' },
        { label: 'Répétition espacée', value: 'spaced_repetition' },
        { label: 'Personnalisé', value: 'custom' },
      ],
    },
    {
      name: 'status',
      label: 'Statut',
      type: 'select',
      defaultValue: 'draft',
      options: [
        { label: 'Brouillon', value: 'draft' },
        { label: 'Actif', value: 'active' },
        { label: 'Terminé', value: 'completed' },
        { label: 'Archivé', value: 'archived' },
      ],
      admin: {
        position: 'sidebar',
      },
    },
    {
      name: 'user',
      label: 'Étudiant',
      type: 'relationship',
      relationTo: 'users',
      hasMany: false,
      required: true,
      admin: {
        position: 'sidebar',
      },
    },
    {
      name: 'weekStart',
      label: 'Début de semaine',
      type: 'date',
      admin: {
        position: 'sidebar',
        date: {
          pickerAppearance: 'dayOnly',
        },
      },
    },
    {
      name: 'weekEnd',
      label: 'Fin de semaine',
      type: 'date',
      admin: {
        position: 'sidebar',
        date: {
          pickerAppearance: 'dayOnly',
        },
      },
    },
    {
      name: 'objective',
      label: 'Objectifs de la semaine',
      type: 'textarea',
    },
    {
      name: 'plannedDurationMinutes',
      label: 'Durée planifiée (minutes)',
      type: 'number',
      min: 0,
      admin: {
        position: 'sidebar',
        description: 'Somme des durées prévues dans les créneaux',
        readOnly: true,
      },
    },
    {
      name: 'actualDurationMinutes',
      label: 'Durée réalisée (minutes)',
      type: 'number',
      min: 0,
      admin: {
        position: 'sidebar',
        readOnly: true,
      },
    },
    {
      name: 'autoGenerated',
      label: 'Plan généré automatiquement',
      type: 'checkbox',
      defaultValue: false,
      admin: {
        position: 'sidebar',
      },
    },
    {
      name: 'slots',
      label: 'Créneaux planifiés',
      type: 'array',
      labels: {
        singular: 'Créneau',
        plural: 'Créneaux',
      },
      fields: [
        {
          name: 'slotId',
          label: 'Identifiant du créneau',
          type: 'text',
          admin: {
            readOnly: true,
            description: 'Peut être utilisé côté frontend pour la synchronisation',
          },
        },
        {
          name: 'title',
          label: 'Titre',
          type: 'text',
          required: true,
        },
        {
          name: 'notes',
          label: 'Notes',
          type: 'textarea',
        },
        {
          name: 'startsAt',
          label: 'Début',
          type: 'date',
          required: true,
          admin: {
            date: {
              pickerAppearance: 'dayAndTime',
              displayFormat: 'dd/MM/yyyy HH:mm',
            },
          },
        },
        {
          name: 'durationMinutes',
          label: 'Durée (minutes)',
          type: 'number',
          required: true,
          min: 5,
          max: 240,
        },
        {
          name: 'activityType',
          label: 'Type d\'activité',
          type: 'select',
          required: true,
          options: [
            { label: 'Spaced Repetition', value: 'spaced_repetition' },
            { label: 'Flashcards', value: 'flashcards' },
            { label: 'Quiz', value: 'quiz' },
            { label: 'Quiz adaptatif', value: 'adaptive_quiz' },
            { label: 'Session d\'étude', value: 'study_session' },
            { label: 'Révision libre', value: 'review' },
            { label: 'Examen blanc', value: 'mock_exam' },
            { label: 'Pause', value: 'break' },
            { label: 'Autre', value: 'custom' },
          ],
        },
        {
          name: 'status',
          label: 'Statut',
          type: 'select',
          defaultValue: 'planned',
          options: [
            { label: 'Prévu', value: 'planned' },
            { label: 'En cours', value: 'in_progress' },
            { label: 'Terminé', value: 'completed' },
            { label: 'Manqué', value: 'missed' },
            { label: 'Annulé', value: 'canceled' },
          ],
        },
        {
          name: 'linkedQuiz',
          label: 'Quiz associé',
          type: 'relationship',
          relationTo: 'quizzes',
          admin: {
            condition: (_, siblingData) => siblingData.activityType === 'quiz' || siblingData.activityType === 'adaptive_quiz',
          },
        },
        {
          name: 'linkedStudySession',
          label: 'Session d\'étude associée',
          type: 'relationship',
          relationTo: 'study-sessions',
          admin: {
            condition: (_, siblingData) => siblingData.activityType === 'study_session' || siblingData.activityType === 'spaced_repetition',
          },
        },
        {
          name: 'metadata',
          label: 'Métadonnées',
          type: 'json',
        },
      ],
    },
    {
      name: 'srsScheduleData',
      label: 'Planning répétition espacée (JSON)',
      type: 'textarea',
      admin: {
        description: 'Données SRS sérialisées pour les plannings de répétition espacée',
        readOnly: true,
        condition: (data) => data.planType === 'spaced_repetition',
      },
    },
    {
      name: 'metadata',
      label: 'Métadonnées supplémentaires',
      type: 'json',
      admin: {
        description: 'Stocke les informations de génération automatique, objectifs spécifiques, etc.',
      },
    },
  ],
};

export default StudyPlans;
